### ISSUE TITLE
Ground Truth Data Format

### ISSUE THREAD

**Issue by plpalmer** [prs-eth/PCAccumulation#6]
Hi, thank you for the great project.

I would like to adapt other datasets to use with this Code but i am facing some issues in the GT generation.

Is there a timeline on when you plan to publish the preprocessing code or could you elaborate on the ground truth data format? Especially on what time indices represents the "current" frame and if the ego_motion_gt/bbox_tsfm represent the transformation between some previous and the current frame or between two adjacent frames.

Thanks in advance

**Comment by RaymondByc** [comment]
Hi, would you like to release the pre-process code this month?

Are there differences with FastFlow3D?

**Comment by ShengyuH** [comment]
@plpalmer hi, thank you for your interest in our project. Please excuse me for this super late reply, I will upload some scripts used for GT data generation now, they are not immediately runnable but contain most of the functions I used to create the dataset. As we mentioned in the paper, "We denote the first frame X 1 the target frame, while the remaining frames { X t | t > 1 } are termed source frames.", and ego_motion_gt/bbox_tsfm represent the transformation between some previous and the current frame. 

@RaymondByc  Please check the dataset_toolbox folder.

**Comment by RaymondByc** [comment]
thanks for your reply. I am checking your preprocessing code, but it seems that the code related to the "lidarrec_oracle" folder which obtains the "est_tsfm" label and "inst_labels" is missing. 

I appreciate it if you upload related code.

**Comment by ShengyuH** [comment]
```"lidarrec_oracle``` was used for other tasks and is not relevant to this project. I failed to mention that my preprocessing code is mostly based on the toolboxes provided by [waymo](https://github.com/waymo-research/waymo-open-dataset) and [nuscene](https://github.com/nutonomy/nuscenes-devkit), I was mostly extracting the flow vectors from the odometry and tracking information and re-organising the dataset.

**Comment by ShengyuH** [comment]
close due to in-activity.
