### ISSUE TITLE
About visualization method

### ISSUE THREAD

**Issue by NorthSummer** [prs-eth/PCAccumulation#7]
Hi! Thanks for OA the brilliant work! Can I ask for a copy of visualization code of this work? Thx

**Comment by NorthSummer** [comment]
Thanks for the reply, and another question is that: what does the long strings stand for in the developed nuscenes dataset. e.g. 8d8728879b89405eba3f8ce1af138cb2/08aef4d81f2f48c1b02599899dda3dae.npz, I find "8d8728879b89405eba3f8ce1af138cb2" is not a scene token, and what does it stand for? Is the data matched one by one with the original nuscenes dataset? Thanks very much and looking forward for your reply!

**Comment by ShengyuH** [comment]
Close due to in-activity.

**Comment by NorthSummer** [comment]
Hi, I want to ask about the surface reconstruction. Does this part have GT labels?

**Comment by ShengyuH** [comment]
No, we just applied PSR.

**Comment by NorthSummer** [comment]
So the normal vectors are obtained(estimated) by open3d....?

**Comment by ShengyuH** [comment]
Yes.

**Comment by NorthSummer** [comment]
Roger, thanks a lot!

**Comment by lsn33096** [comment]
Hi,

Could you please share the visualization script? Thanks!
